name: Github Pages
on: push
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src/web
